### ISSUE TITLE
Prebuilt apk 1.0 app crashes on version 1.4.6 of X9S

### ISSUE THREAD

**Issue by scottmatheson** [zidootech/ZidooDigitalSignage#1]
1) Install ZidooDigitalDemo_1.1.apk.
2) Run app and select "Hdmi in" from Main activity grid.
3) Hit Return on remote to exit "Hdmi in" to go back to Main activity.
4) App crashes in call from RtkHDMIRxManager release().

**Comment by zidootech** [comment]
Hi, Please build the demo apk yourself.  Using 'export'  and sign the apk with a key.

**Comment by scottmatheson** [comment]
Building the demo from source.  Install app on 1.4.6.  Give permissions to app.  Follow steps 2 and 3 above.  The app crashes in call to RtkHDMIRxManager release().
Correct me if I'm wrong, but signing is only needed if you need to record?

**Comment by daolong** [comment]
I uploaded demo apk to 1.4  Please pull and try.  
Signing is the way to fix the crash issue.

**Comment by zidootech** [comment]
I uploaded apk to version 1.4. plase download and try
Signing is the way to fix crash issue.

**Comment by scottmatheson** [comment]
Yes, the version 1.4 APK does not crash.  All builds from source must be explicitly signed to work.  Android Studio (when using the debugger) signs the app before installing, however that signing mechanism is insufficient.  I would suggest in the repos README adding instructions on how to modify the gradle settings to get the apps signed correctly for debugging.
